on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: starting build stage
              shell: bash
              run: echo "beginning"
            - name: login to dockerhub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: build seed data
              uses: docker/build-push-action@v2
              with:
                context: "./seed-data"
                push: ${{ github.event_name != 'pull_request' }}
                tags: ibrahimefe/seed-data
                cache-from: type=gha
                cache-to: type=gha,mode=max
            - name: build vote
              uses: docker/build-push-action@v2
              with:
                context: "./vote"
                push: ${{ github.event_name != 'pull_request' }}
                tags: ibrahimefe/vote
                cache-from: type=gha
                cache-to: type=gha,mode=max
            - name: build worker
              uses: docker/build-push-action@v2
              with:
                context: "./worker"
                push: ${{ github.event_name != 'pull_request' }}
                tags: ibrahimefe/worker
                cache-from: type=gha
                cache-to: type=gha,mode=max
           
