on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
            - uses: actions/checkout@v3
            - name: starting build stage
            - shell: bash
              run: echo "beginning"
            - name: build-seed-data
              working-directory: ./seed-data
              run: echo "Building image" |
                docker build -t seed-data .
