on:
    push:
        branches:
          - main
    pull_request:
jobs:
    build:
        permissions:
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: starting build stage
              shell: bash
              run: echo "beginning"
            - name: login to dockerhub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: setup buildx
              uses: docker/setup-buildx-action@v2
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v4
              with:
                images: |
                    ibrahimefe/worker
                    ibrahimefe/vote
                    ibrahimefe/seed-data
                    ibrahimefe/result
                tags: |
                    type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
                    type=ref,event=pr
                    type=semver,pattern={{version}}
                    type=semver,pattern={{major}}.{{minor}}

            - name: Build images
              uses: docker/build-push-action@v4
              with:
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                platforms: linux/amd64,linux/arm64, linux/arm/v7
                cache-from: type=gha
                cache-to: type=gha,mode=max
            - name: Find Comment
              uses: peter-evans/find-comment@v2
              if: ${{ github.event_name == 'pull_request' }}
              id: fc
              with:
                issue-number: ${{ github.event.pull_request.number }}
                comment-author: 'github-actions[bot]'
                body-includes: Image(s) built
            - name: Create or update comment
              uses: peter-evans/create-or-update-comment@v3
              if: ${{ github.event_name == 'pull_request' }}
              with:
                comment-id: ${{ steps.fc.outputs.comment-id }}
                issue-number: ${{ github.event.pull_request.number }}
                body: |
                  Image tag(s) pushed
                  ```text
                  ${{ steps.meta.outputs.tags }}
                  ```
                  Labels added:
                  ```text
                  ${{ steps.meta.outputs.labels }}
                  ```
                edit-mode: replace

