on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - shell: bash
              run: |
                echo "beginning"
            - name: build-seed-data
              run: ls | docker build -t seed-data .
