on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: starting build stage
              shell: bash
              run: echo "beginning"
            - name: login to dockerhub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: build seed data
              uses: docker/build-push-action@v4
              with:
                context: "./seed-data"
                tags: ibrahimefe/seed-data
            - name: build vote
              uses: docker/build-push-action@v4
              with:
                context: "./vote"
                tags: ibrahimefe/vote
            - name: build worker
              uses: docker/build-push-action@v4
              with:
                context: "./worker"
                tags: ibrahimefe/worker
           
