on:
    push:
        branches:
          - main
    pull_request:
jobs:
    build:
        permissions:
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: starting build stage
              shell: bash
              run: echo "beginning"
            - name: login to dockerhub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: setup buildx
              uses: docker/setup-buildx-action@v2
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: build seed data
              uses: docker/build-push-action@v4
              with:
                context: "./seed-data"
                push: false
                load: true
                tags: ${{ github.run_id }}
                labels: ${{ steps.meta.outputs.labels }}
                platforms: linux/amd64
                cache-from: type=gha
                cache-to: type=gha,mode=max
            - name: build vote
              uses: docker/build-push-action@v4
              with:
                context: "./vote"
                push: false
                load: true
                tags: ${{ github.run_id }}
                labels: ${{ steps.meta.outputs.labels }}
                platforms: linux/amd64
                cache-from: type=gha
                cache-to: type=gha,mode=max
            - name: build worker
              uses: docker/build-push-action@v4
              with:
                context: "./worker"
                push: false
                load: true
                tags: ${{ github.run_id }}
                labels: ${{ steps.meta.outputs.labels }}
                platforms: linux/amd64
                cache-from: type=gha
                cache-to: type=gha,mode=max
            - name: build result
              uses: docker/build-push-action@v4
              with:
                context: "./result"
                push: false
                load: true
                tags: ${{ github.run_id }}
                labels: ${{ steps.meta.outputs.labels }}
                platforms: linux/amd64
            - name: Run Trivy for all CVEs (non-blocking)
              uses: aquasecurity/trivy-action@master
              with:
                image-ref: ${{ github.run_id }}
                exit-code: 0
                format: table
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v4
              with:
                images: |
                    ibrahimefe/worker
                    ibrahimefe/vote
                    ibrahimefe/seed-data
                    ibrahimefe/result
                tags: |
                    type=raw,value=02
            - name: build seed data
              uses: docker/build-push-action@v4
              with:
                context: "./seed-data"
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                platforms: linux/amd64,linux/arm64, linux/arm/v7
                cache-from: type=gha
                cache-to: type=gha,mode=max
            - name: build vote
              uses: docker/build-push-action@v4
              with:
                context: "./vote"
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                platforms: linux/amd64,linux/arm64, linux/arm/v7
                cache-from: type=gha
                cache-to: type=gha,mode=max
            - name: build worker
              uses: docker/build-push-action@v4
              with:
                context: "./worker"
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                platforms: linux/amd64,linux/arm64, linux/arm/v7
                cache-from: type=gha
                cache-to: type=gha,mode=max
            - name: build result
              uses: docker/build-push-action@v4
              with:
                context: "./result"
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                platforms: linux/amd64,linux/arm64, linux/arm/v7
