
on:
    push:
        branches:
          - main
    pull_request:
jobs:
    build:
        permissions:
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: starting build stage
              shell: bash
              run: echo "beginning"
            - name: login to dockerhub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: setup buildx
              uses: docker/setup-buildx-action@v2
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: build seed data
              uses: docker/build-push-action@v4
              with:
                context: "./seed-data"
                push: false
                load: true
                tags: ${{ github.run_id }}/seed-data
                platforms: linux/amd64
                cache-from: type=gha
                cache-to: type=gha,mode=max
            - name: seed-date unit tests
              run: |
                docker run --rm ${{ github.run_id }}/seed-data echo "running unit tests for seed-data"
            - name: build vote
              uses: docker/build-push-action@v4
              with:
                context: "./vote"
                push: false
                load: true
                tags: ${{ github.run_id }}/vote
                platforms: linux/amd64
                cache-from: type=gha
                cache-to: type=gha,mode=max
            - name: vote unit tests
              run: |
                docker run --rm ${{ github.run_id }}/vote echo "running unit tests for vote"
            - name: build worker
              uses: docker/build-push-action@v4
              with:
                context: "./worker"
                push: false
                load: true
                tags: ${{ github.run_id }}/worker
                platforms: linux/amd64
                cache-from: type=gha
                cache-to: type=gha,mode=max
            - name: worker unit tests
              run: |
                docker run --rm ${{ github.run_id }}/worker echo "running unit tests for worker"
            - name: build result
              uses: docker/build-push-action@v4
              with:
                context: "./result"
                push: false
                load: true
                tags: ${{ github.run_id }}/result
                platforms: linux/amd64
            - name: result unit tests
              run: |
                docker run --rm ${{ github.run_id }}/result echo "running unit tests for result"
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v4
              with:
                images: |
                    ibrahimefe/worker
                    ibrahimefe/vote
                    ibrahimefe/seed-data
                    ibrahimefe/result
                tags: |
                    type=raw,value=05

            - name: build seed data
              uses: docker/build-push-action@v4
              with:
                context: "./seed-data"
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                platforms: linux/amd64,linux/arm64, linux/arm/v7
                cache-from: type=gha
                cache-to: type=gha,mode=max
            - name: build vote
              uses: docker/build-push-action@v4
              with:
                context: "./vote"
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                platforms: linux/amd64,linux/arm64, linux/arm/v7
                cache-from: type=gha
                cache-to: type=gha,mode=max
            - name: build worker
              uses: docker/build-push-action@v4
              with:
                context: "./worker"
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                platforms: linux/amd64,linux/arm64, linux/arm/v7
                cache-from: type=gha
                cache-to: type=gha,mode=max
            - name: build result
              uses: docker/build-push-action@v4
              with:
                context: "./result"
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                platforms: linux/amd64,linux/arm64, linux/arm/v7
