name: integration testing
on:
    push:
        branches:
          - main
    pull_request:
jobs:
    build:
        permissions:
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: starting build stage
              shell: bash
              run: echo "beginning"
            - name: login to dockerhub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: setup buildx
              uses: docker/setup-buildx-action@v2
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: build seed data
              uses: docker/build-push-action@v4
              with:
                context: "./seed-data"
                push: false
                load: true
                tags: ${{ github.run_id }}/seed-data
                platforms: linux/amd64
                cache-from: type=gha
                cache-to: type=gha,mode=max
            - name: build vote
              uses: docker/build-push-action@v4
              with:
                context: "./vote"
                push: false
                load: true
                tags: ${{ github.run_id }}/vote
                platforms: linux/amd64
                cache-from: type=gha
                cache-to: type=gha,mode=max
            - name: build worker
              uses: docker/build-push-action@v4
              with:
                context: "./worker"
                push: false
                load: true
                tags: ${{ github.run_id }}/worker
                platforms: linux/amd64
                cache-from: type=gha
                cache-to: type=gha,mode=max
            - name: build result
              uses: docker/build-push-action@v4
              with:
                context: "./result"
                push: false
                load: true
                tags: ${{ github.run_id }}/result
                platforms: linux/amd64

            - name: integration test in docker-compose
              run: |
                export VOTE_IMAGE=${{ github.run_id }}/vote
                export RESULT_IMAGE=${{ github.run_id }}/result
                export WORKER_IMAGE=${{ github.run_id }}/worker
                docker-compose -f docker-compose.test.yml up --build -d --exit-code-from vote

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v4
              with:
                images: |
                    ibrahimefe/worker
                    ibrahimefe/vote
                    ibrahimefe/seed-data
                    ibrahimefe/result
                tags: |
                    type=raw,value=06

            - name: build seed data
              uses: docker/build-push-action@v4
              with:
                context: "./seed-data"
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                platforms: linux/amd64,linux/arm64, linux/arm/v7
                cache-from: type=gha
                cache-to: type=gha,mode=max
            - name: build vote
              uses: docker/build-push-action@v4
              with:
                context: "./vote"
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                platforms: linux/amd64,linux/arm64, linux/arm/v7
                cache-from: type=gha
                cache-to: type=gha,mode=max
            - name: build worker
              uses: docker/build-push-action@v4
              with:
                context: "./worker"
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                platforms: linux/amd64,linux/arm64, linux/arm/v7
                cache-from: type=gha
                cache-to: type=gha,mode=max
            - name: build result
              uses: docker/build-push-action@v4
              with:
                context: "./result"
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                platforms: linux/amd64,linux/arm64, linux/arm/v7


